<?php

/**
 * Display the hours for all library locations in one
 * table grid
 */
function dul_hours_table_page() {
	// ROADMAP:
	// 1) Retrieve the library ids (perkins, public, etc)
	// 2) For each, fetch a week's worth of data
	//    -- determine closest "previous" Sunday and upcoming "Saturday"
	// 3) Build a table for the display.
	return array();
}

/**
 * Display the hours for a single library in a calendar table view
 * TODO: Investigate leveraging the Views module for this.
 */
function dul_hours_library_calendar_page() {
	return array();
}

